# Generated by Django 5.2.8 on 2025-12-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LangArt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='short_tag',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
