# Generated by Django 5.2.8 on 2025-12-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LangArt', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_overview',
            field=models.TextField(default='Course overview'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='how_much_1stars',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='how_much_2stars',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='how_much_3stars',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='how_much_4stars',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='how_much_5stars',
            field=models.IntegerField(default=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='what_you_will_learn',
            field=models.JSONField(default=list),
        ),
    ]
